# Generated by Django 3.2.15 on 2022-09-27 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220926_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='email',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='last_name',
        ),
    ]
