# Generated by Django 3.2.15 on 2022-09-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220927_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='paid_amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
