# Generated by Django 3.2.15 on 2022-09-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_orders_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='email',
            field=models.EmailField(default='masuba@gmail.com', max_length=64),
        ),
        migrations.AddField(
            model_name='orders',
            name='first_name',
            field=models.CharField(default='masuba', max_length=30),
        ),
        migrations.AddField(
            model_name='orders',
            name='last_name',
            field=models.CharField(default='abdqadir', max_length=30),
        ),
    ]
