# Generated by Django 3.2.15 on 2022-09-29 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_file'),
        ('products', '0006_auto_20220928_1044'),
    ]

    operations = [
    ]
