# Generated by Django 3.2.15 on 2022-09-29 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20220929_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_status',
        ),
    ]
