# Generated by Django 3.2.15 on 2022-09-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_orders_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_status',
            field=models.CharField(default='True', max_length=30),
        ),
    ]
