# Generated by Django 3.2.15 on 2022-09-29 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_file'),
        ('products', '0009_orders_order_status'),
    ]

    operations = [
    ]
