# Generated by Django 3.2.15 on 2022-09-30 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_merge_0004_product_file_0006_auto_20220928_1044'),
        ('products', '0010_merge_0004_product_file_0009_orders_order_status'),
    ]

    operations = [
    ]
