# Generated by Django 3.2.15 on 2022-09-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220924_0824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name_plural': '1. Banners'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '2. Categories'},
        ),
        migrations.AddField(
            model_name='color',
            name='image',
            field=models.ImageField(default=1, upload_to='color_imgs/'),
            preserve_default=False,
        ),
    ]
