# Generated by Django 3.2.15 on 2022-09-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220925_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=200),
            preserve_default=False,
        ),
    ]
