# Generated by Django 3.2.15 on 2022-09-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='price',
            field=models.PositiveIntegerField(default=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='color',
            name='price',
            field=models.PositiveIntegerField(default=200),
            preserve_default=False,
        ),
    ]
